services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: a12345678
      KC_HTTP_RELATIVE_PATH: /auth
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    ports:
      - "8080:8080"

  oauth-api:
    build: .
    container_name: oauth-api
    ports:
      - "8081:8081"
    environment:
      KEYCLOAK_URL: http://keycloak:8080/auth
      KEYCLOAK_REALM: constr-sw-2026-2
      KEYCLOAK_CLIENT_ID: oauth
      KEYCLOAK_CLIENT_SECRET: o1nlFjJcpqhSL34dzQ0avGyDrkZZ1J58
    depends_on:
      - keycloak
