server:
  port: ${OAUTH_INTERNAL_API_PORT:8081}

keycloak:
  url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:constrsw}
  client-id: ${KEYCLOAK_CLIENT_ID:oauth}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:wsNXUxaupU9X6jCncsn3rOEy6PDt7oJO}

logging:
  level:
    br.pucrs.constrsw: DEBUG

spring:
  application:
    name: oauth-api

management:
  server:
    port: ${OAUTH_INTERNAL_METRICS_PORT:9464}
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: oauth-api
  tracing:
    sampling:
      probability: 1.0

