parameters:
    keycloak.base_url: '%env(KEYCLOAK_INTERNAL_URL)%'
    keycloak.realm: '%env(KEYCLOAK_REALM)%'
    keycloak.client_id: '%env(KEYCLOAK_CLIENT_ID)%'
    keycloak.client_secret: '%env(KEYCLOAK_CLIENT_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/Model/'
            - '../src/Domain/Exception/'
            - '../src/Application/DTO/'
            - '../src/Kernel.php'

    App\Infrastructure\Http\Controller\:
        resource: '../src/Infrastructure/Http/Controller/'
        tags: ['controller.service_arguments']

    App\Infrastructure\Keycloak\Client\KeycloakHttpClient:
        arguments:
            $baseUrl: '%keycloak.base_url%'
            $realm: '%keycloak.realm%'
            $clientId: '%keycloak.client_id%'
            $clientSecret: '%keycloak.client_secret%'

    App\Infrastructure\Http\Listener\JsonExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 10 }
